melhora navegação do database
YuriAlessandro/gerador-ficha-tormenta20 pull request #361
Opened 2023-09-15 00:40 UTC by fabioars

- No mobile e no desktop, a navegação permanece na tela durante o scroll
- No mobile os botões de navegação ficam alinhados em um grid

![image](https://github.com/YuriAlessandro/gerador-ficha-tormenta20/assets/5921856/b3ae25a0-b371-478c-ab43-47a624a051ef)

![image](https://github.com/YuriAlessandro/gerador-ficha-tormenta20/assets/5921856/2b5e7fed-755d-4a33-8c48-ba55f455c4ef)

2023-09-15 01:15 UTC, fabioars commented
- Muda o header pra 100% da tela

![image](https://github.com/YuriAlessandro/gerador-ficha-tormenta20/assets/5921856/232dee5d-b3f9-47e0-9ba1-bf7c0f988a99)

2023-09-15 11:31 UTC, YuriAlessandro requested changes
Acho que pode manter o header como estava, por agora. 

De restante, parece interessante.

2023-09-15 11:31 UTC, YuriAlessandro commented on src/App.tsx
>                      >
Acho que pode manter o header meio "flutuante" como estava. Eu tinha deixado daquele jeito para dar um visual diferente e deixar ele mais clean.

2023-09-15 11:53 UTC, fabioars commented on src/App.tsx
>                      >
Prontinho!

2023-10-02 16:19 UTC, YuriAlessandro approved these changes

2023-10-02 16:19 UTC, merged